const std = @import("std");

pub fn build(b: *std.Build) void {
    const optimize = b.standardOptimizeOption(.{});
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .x86_64,
        .os_tag = .freestanding,
        .abi = .none,
    });

    const root_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/main.zig"), .target = target, .optimize = optimize });
    const mm_core_mod = b.createModule(.{ .root_source_file = b.path("mm/core.zig"), .target = target, .optimize = optimize });
    const mm_phys_mod = b.createModule(.{ .root_source_file = b.path("mm/phys.zig"), .target = target, .optimize = optimize });
    const fs_vfs_mod = b.createModule(.{ .root_source_file = b.path("fs/vfs.zig"), .target = target, .optimize = optimize });
    const fs_fat32_mod = b.createModule(.{ .root_source_file = b.path("fs/fat32.zig"), .target = target, .optimize = optimize });
    const fs_iso_stub_mod = b.createModule(.{ .root_source_file = b.path("fs/iso9660_stub.zig"), .target = target, .optimize = optimize });
    const gfx_fb_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/gfx/framebuffer.zig"), .target = target, .optimize = optimize });
    const util_ring_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/util/ringbuf.zig"), .target = target, .optimize = optimize });
    const util_seqlock_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/util/seqlock.zig"), .target = target, .optimize = optimize });
    const util_mpmc_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/util/mpmc.zig"), .target = target, .optimize = optimize });
    const util_radix_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/util/radix/tree.zig"), .target = target, .optimize = optimize });
    const io_blk_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/io/blk.zig"), .target = target, .optimize = optimize });
    const drv_ramdisk_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/drivers/ramdisk.zig"), .target = target, .optimize = optimize });
    const evt_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/event/events.zig"), .target = target, .optimize = optimize });
    const cap_types_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/cap/types.zig"), .target = target, .optimize = optimize });
    const cap_api_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/cap/cap_api.zig"), .target = target, .optimize = optimize });
    const cap_epoch_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/cap/epoch.zig"), .target = target, .optimize = optimize });
    cap_api_mod.addImport("cap_types", cap_types_mod);
    _ = b.createModule(.{ .root_source_file = b.path("src/kernel/cap/epoch.zig"), .target = target, .optimize = optimize });
    const win_pe_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/pe.zig"), .target = target, .optimize = optimize });
    const win_handle_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/handle.zig"), .target = target, .optimize = optimize });
    const win_process_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/process.zig"), .target = target, .optimize = optimize });
    const win_thread_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/thread.zig"), .target = target, .optimize = optimize });
    const win_api_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/api.zig"), .target = target, .optimize = optimize });
    const win_object_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/object.zig"), .target = target, .optimize = optimize });
    const evt_shmq_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/event/shmq.zig"), .target = target, .optimize = optimize });
    const win_context_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/context.zig"), .target = target, .optimize = optimize });
    const win_syscall_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/win/syscall.zig"), .target = target, .optimize = optimize });
    const compat_atomic_mod = b.createModule(.{ .root_source_file = b.path("compat/atomic.zig"), .target = target, .optimize = optimize });
    const abi_persona_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/abi/persona.zig"), .target = target, .optimize = optimize });
    const abi_linux_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/abi/linux.zig"), .target = target, .optimize = optimize });
    const abi_bsd_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/abi/bsd.zig"), .target = target, .optimize = optimize });
    const libos_linux_elf_mod = b.createModule(.{ .root_source_file = b.path("src/kernel/libos/linux/elf.zig"), .target = target, .optimize = optimize });
    fs_iso_stub_mod.addImport("fs_vfs", fs_vfs_mod);
    fs_vfs_mod.addImport("cap_types", cap_types_mod);
    fs_vfs_mod.addImport("cap_api", cap_api_mod);
    fs_vfs_mod.addImport("cap_epoch", cap_epoch_mod);
    fs_vfs_mod.addImport("util_radix_tree", util_radix_mod);
    fs_fat32_mod.addImport("io_blk", io_blk_mod);
    fs_fat32_mod.addImport("fs_vfs", fs_vfs_mod);
    root_mod.addImport("fs_fat32", fs_fat32_mod);
    evt_mod.addImport("util_ring", util_ring_mod);
    evt_mod.addImport("event_shmq", evt_shmq_mod);
    evt_mod.addImport("util_mpmc", util_mpmc_mod);
    evt_mod.addImport("cap_types", cap_types_mod);
    evt_mod.addImport("cap_api", cap_api_mod);
    evt_mod.addImport("cap_epoch", cap_epoch_mod);
    util_mpmc_mod.addImport("cap_epoch", cap_epoch_mod);
    mm_core_mod.addImport("util_radix_tree", util_radix_mod);
    root_mod.addImport("util_radix_tree", util_radix_mod);
    root_mod.addImport("io_blk", io_blk_mod);
    root_mod.addImport("drv_ramdisk", drv_ramdisk_mod);
    drv_ramdisk_mod.addImport("io_blk", io_blk_mod);
    root_mod.addImport("cap_epoch", cap_epoch_mod);
    root_mod.addImport("mm_core", mm_core_mod);
    root_mod.addImport("mm_phys", mm_phys_mod);
    root_mod.addImport("fs_vfs", fs_vfs_mod);
    root_mod.addImport("fs_iso_stub", fs_iso_stub_mod);
    root_mod.addImport("util_ring", util_ring_mod);
    root_mod.addImport("events", evt_mod);
    root_mod.addImport("util_seqlock", util_seqlock_mod);
    root_mod.addImport("gfx_fb", gfx_fb_mod);
    root_mod.addImport("win_pe", win_pe_mod);
    root_mod.addImport("win_handle", win_handle_mod);
    root_mod.addImport("win_process", win_process_mod);
    root_mod.addImport("win_thread", win_thread_mod);
    root_mod.addImport("win_api", win_api_mod);
    root_mod.addImport("win_object", win_object_mod);
    root_mod.addImport("event_shmq", evt_shmq_mod);
    root_mod.addImport("compat_atomic", compat_atomic_mod);
    root_mod.addImport("win_context", win_context_mod);
    root_mod.addImport("win_syscall", win_syscall_mod);
    root_mod.addImport("abi_persona", abi_persona_mod);
    root_mod.addImport("abi_linux", abi_linux_mod);
    root_mod.addImport("abi_bsd", abi_bsd_mod);
    win_process_mod.addImport("fs_vfs", fs_vfs_mod);
    win_process_mod.addImport("win_pe", win_pe_mod);
    win_process_mod.addImport("win_handle", win_handle_mod);
    win_process_mod.addImport("abi_persona", abi_persona_mod);
    util_ring_mod.addImport("compat_atomic", compat_atomic_mod);
    util_seqlock_mod.addImport("compat_atomic", compat_atomic_mod);
    evt_shmq_mod.addImport("compat_atomic", compat_atomic_mod);
    util_mpmc_mod.addImport("compat_atomic", compat_atomic_mod);
    win_api_mod.addImport("fs_vfs", fs_vfs_mod);
    win_api_mod.addImport("win_handle", win_handle_mod);
    win_api_mod.addImport("win_object", win_object_mod);
    win_thread_mod.addImport("win_handle", win_handle_mod);
    win_syscall_mod.addImport("win_api", win_api_mod);
    win_syscall_mod.addImport("win_handle", win_handle_mod);
    abi_persona_mod.addImport("win_syscall", win_syscall_mod);
    abi_persona_mod.addImport("abi_linux", abi_linux_mod);
    abi_persona_mod.addImport("abi_bsd", abi_bsd_mod);
    abi_linux_mod.addImport("fs_vfs", fs_vfs_mod);
    abi_linux_mod.addImport("events", evt_mod);
    abi_bsd_mod.addImport("fs_vfs", fs_vfs_mod);
    abi_bsd_mod.addImport("events", evt_mod);
    abi_linux_mod.addImport("libos_elf", libos_linux_elf_mod);
    win_object_mod.addImport("win_handle", win_handle_mod);
    win_object_mod.addImport("compat_atomic", compat_atomic_mod);
    win_pe_mod.addImport("mm_core", mm_core_mod);
    win_pe_mod.addImport("win_api", win_api_mod);
    win_pe_mod.addImport("win_handle", win_handle_mod);
    const exe = b.addExecutable(.{ .name = "uya-kernel", .root_module = root_mod });
    root_mod.link_libc = false;
    exe.entry = .{ .symbol_name = "_start" };
    exe.linker_script = b.path("linker.ld");
    b.installArtifact(exe);
    const host_target = b.resolveTargetQuery(.{ .cpu_arch = .x86_64, .os_tag = .windows });
    const uyade_mod = b.createModule(.{ .root_source_file = b.path("apps/uyade/main.zig"), .target = host_target, .optimize = optimize });
    const uyade = b.addExecutable(.{ .name = "uyade", .root_module = uyade_mod });
    b.installArtifact(uyade);
    const reg_mod = b.createModule(.{ .root_source_file = b.path("apps/registry/cli.zig"), .target = host_target, .optimize = optimize });
    const worktree_path = "apps/registry/worktree_win.zig";
    const reg_worktree_mod = b.createModule(.{ .root_source_file = b.path(worktree_path), .target = host_target, .optimize = optimize });
    reg_mod.addImport("worktree_mod", reg_worktree_mod);
    const reg_cli = b.addExecutable(.{ .name = "uya-registry", .root_module = reg_mod });
    b.installArtifact(reg_cli);
    const reg_srv_mod = b.createModule(.{ .root_source_file = b.path("apps/registry/server.zig"), .target = host_target, .optimize = optimize });
    const reg_srv = b.addExecutable(.{ .name = "uya-registry-server", .root_module = reg_srv_mod });
    b.installArtifact(reg_srv);
}
